#!/bin/bash

source /opt/ros/humble/setup.bash
source ~/colcon_ws/install/setup.bash

sleep 5

export ROS_HOSTNAME=scout
export ROS_MASTER_URI=http://scout:11311
export ROS_HOME=~/.ros

ros2 launch roas2_bringup bringup.launch.py
